# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_auto_20170901_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioschedule',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Place'),
        ),
        migrations.AlterField(
            model_name='studiouser',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Place'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Place'),
        ),
    ]
