# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0004_auto_20170801_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio_calendar',
            name='From',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studio_calendar',
            name='To',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 1, 23, 9, 56, 682784, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studio_calendar',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studio_calendar',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
