# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0005_auto_20170801_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio_calendar',
            old_name='From',
            new_name='Operate_From',
        ),
        migrations.RenameField(
            model_name='studio_calendar',
            old_name='To',
            new_name='Operate_To',
        ),
        migrations.RenameField(
            model_name='studio_calendar',
            old_name='name',
            new_name='Owner_name',
        ),
        migrations.RenameField(
            model_name='studio_calendar',
            old_name='studio',
            new_name='Studio_name',
        ),
        migrations.RenameField(
            model_name='studio_calendar',
            old_name='teacher',
            new_name='Teacher_name',
        ),
    ]
