# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0006_auto_20170814_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio_calendar',
            name='Hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
