# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0007_studio_calendar_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=120)),
                ('Date', models.DateField(null=True)),
                ('User_booked_from', models.TimeField()),
                ('User_booked_to', models.TimeField()),
                ('User_actually_from', models.TimeField()),
                ('User_actually_to', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='studio_calendar',
            name='Hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user_calendar',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.studio_calendar'),
        ),
    ]
